/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PVButton: typeof import('primevue/button')['default']
    PVCheckbox: typeof import('primevue/checkbox')['default']
    PVDialog: typeof import('primevue/dialog')['default']
    PVDivider: typeof import('primevue/divider')['default']
    PVFloatLabel: typeof import('primevue/floatlabel')['default']
    PVInputNumber: typeof import('primevue/inputnumber')['default']
    PVInputText: typeof import('primevue/inputtext')['default']
    PVKnob: typeof import('primevue/knob')['default']
    PVMenubar: typeof import('primevue/menubar')['default']
    PVPassword: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
