/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeButton: typeof import('primevue/button')['default']
    PrimeDatePicker: typeof import('primevue/datepicker')['default']
    PrimeDialog: typeof import('primevue/dialog')['default']
    PrimeDivider: typeof import('primevue/divider')['default']
    PrimeFloatLabel: typeof import('primevue/floatlabel')['default']
    PrimeInputNumber: typeof import('primevue/inputnumber')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeKnob: typeof import('primevue/knob')['default']
    PrimeMenubar: typeof import('primevue/menubar')['default']
    PrimePassword: typeof import('primevue/password')['default']
    PrimeSplitButton: typeof import('primevue/splitbutton')['default']
    PrimeToggleButton: typeof import('primevue/togglebutton')['default']
    PVButton: typeof import('primevue/button')['default']
    PVCard: typeof import('primevue/card')['default']
    PVCheckbox: typeof import('primevue/checkbox')['default']
    PVDatePicker: typeof import('primevue/datepicker')['default']
    PVDialog: typeof import('primevue/dialog')['default']
    PVDivider: typeof import('primevue/divider')['default']
    PVFloatLabel: typeof import('primevue/floatlabel')['default']
    PVInputNumber: typeof import('primevue/inputnumber')['default']
    PVInputText: typeof import('primevue/inputtext')['default']
    PVKnob: typeof import('primevue/knob')['default']
    PVMenubar: typeof import('primevue/menubar')['default']
    PVPassword: typeof import('primevue/password')['default']
    PVSplitButton: typeof import('primevue/splitbutton')['default']
    PVToggleButton: typeof import('primevue/togglebutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
